### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by brgkdm** [brgkdm/DayZen-good-first-issue#1]
### **Welcome Message**

- **Purpose**: Greet the user and confirm the successful registration.

- **Design**: A prominent welcome message such as “Welcome, [User's Name]!” helps personalize the experience and adds a friendly touch.

- **Example**: Display a banner or modal that says, "Welcome to [Your App Name], [User’s Name]! We’re glad to have you on board."

**Comment by Naga-Himaja** [comment]
Assign this issue to me

**Comment by brgkdm** [comment]
> Assign this issue to me please

### Subject: Issue Assignment

**Hi [K NAGA HIMAJA],**

I have reviewed your request to take on the issue titled "[[Welcome Message](https://github.com/brgkdm/DayZen-good-first-issue/issues/1#top)]". I am assigning it to you now.

Please feel free to reach out if you have any questions or need further clarification on the requirements. I’m looking forward to your contributions!

_Best regards,
[Berat Gökdemir]_
