### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by brgkdm** [brgkdm/DayZen-good-first-issue#8]
### **Mobile Responsiveness**

- **Purpose:** Ensure the interface is optimized for both desktop and mobile users.

- **Design:** Use a responsive layout that adjusts to different screen sizes, with a collapsible navigation menu for mobile users.
Ensure that buttons and links are easily clickable on touchscreens.

- **Example:** On mobile, use a hamburger menu for navigation and larger touch-friendly buttons for key actions.

**Comment by OmmDevgoswami** [comment]
I have PR this issue with some other improvements. Please have a look.
